# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [3]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [4]:
A = np.arange(1, 16).reshape(3,5)

In [5]:
print(f'axes={A.ndim}')
print(f'shape={A.shape}')
print(f'size={A.size}')
print(f'datatype={A.dtype}')

axes=2
shape=(3, 5)
size=15
datatype=int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [6]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [7]:
print(B - C)
print(B * C)
print(B @ C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [8]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(f'elementwie exponentiate =\n {np.exp(B)}')
print(f'minimum value in matrix = {np.min(B)}')
print(f'minimum value for each row = {np.min(B, axis=1)}')
print(f'minimum value for each column = {np.min(B, axis=0)}')
print(f'index of minimum value = {np.argmin(B)}')
print(f'index of minimum value for each row = {np.argmin(B, axis=1)}')
print(f'sum of all elements = {B.sum()}')
print(f'mean for each column = {B.mean(axis=0)}')
print(f'median for each column = {np.median(B, axis=0)}')

elementwie exponentiate =
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
minimum value in matrix = 1
minimum value for each row = [1 4 7]
minimum value for each column = [1 2 3]
index of minimum value = 0
index of minimum value for each row = [0 0 0]
sum of all elements = 45
mean for each column = [4. 5. 6.]
median for each column = [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [10]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [11]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [12]:
# De index som inte är med anses vara kompletta
# I exemplet ovan är A[1] andra raden med alla kolumner vilket även kan skrivas som A[1, :]
A[1, :]

array([ 6,  7,  8,  9, 10])

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [13]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [15]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [16]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [17]:
# a skapas och blir en array med elementen 0 till 29
# b skapas från a där den skapas till en multidimensionell array med 3 axlar där varje siffra anger hur måna element varje axel har (2,3,5). 
# -1 blir 5 som är resten som finns kvar efter att 2 och 3 har använts.
# b är en 3 dimensionell matris där 3 värden utgör en punkt i ett 3 dimensionellt plan med 3 axlar som används bland annat i linjär algebra

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [18]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [19]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [20]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [66]:
def add_mult_matrices(matrix_1, matrix_2, operation):
    if isinstance(matrix_1, np.ndarray) == False or isinstance(matrix_2, np.ndarray) == False:
        return 'matrix arguments need to be of type ndarray.'
        
    if matrix_1.ndim != 2 or matrix_2.ndim != 2:
        return 'too many axes on ndarray'
        
    if operation == 'add':
        if matrix_1.shape == matrix_2.shape:
            return matrix_1 + matrix_2
        else:
            return 'not same size.'
    elif operation == 'multiply':
        m1_rows, m1_cols = matrix_1.shape
        m2_rows, m2_cols = matrix_2.shape

        print(f'{m1_rows},{m1_cols},{m2_rows},{m2_cols}')
        if m1_cols == m2_rows:
            return matrix_1 @ matrix_2
        else:
            return 'sizes must conform.'
    else:
        return 'operation must be add or multiply.'


In [67]:
import pytest
import ipytest
ipytest.autoconfig()

def test_add_mult_matrices():
    # Add matrices (2, 2)
    assert (add_mult_matrices(np.array([[1,2],[3,4]]), np.array([[1,2],[3,4]]), 'add') == np.array([[2,4],[6,8]])).all()
    # Add matrices (2, 3)
    assert (add_mult_matrices(np.array([[1,2,3],[4,5,6]]), np.array([[1,2,3],[4,5,6]]), 'add') == np.array([[2,4,6],[8,10,12]])).all()
    # Add matrices with different shape
    assert add_mult_matrices(np.array([[1,2],[3,4]]), np.array([[1,2]]), 'add') == 'not same size.'
    # Add matrices when first argument is not a matrix
    assert add_mult_matrices('dummy', np.array([[1,2],[3,4]]), 'add') == 'matrix arguments need to be of type ndarray.'
    # Add matrices when second argument is not a matrix
    assert add_mult_matrices(np.array([[1,2],[3,4]]), True, 'add') == 'matrix arguments need to be of type ndarray.'
    # matrices operation with wrong operation
    assert add_mult_matrices(np.array([[1,2],[3,4]]), np.array([[1,2],[3,4]]), 'addd') == 'operation must be add or multiply.'
    # Multiply matrices (2, 2)
    assert (add_mult_matrices(np.array([[1,2],[3,4]]), np.array([[1,2],[3,4]]), 'multiply') == np.array([[7,10],[15,22]])).all()
    # Multiply matrices (2, 3) @ (3, 2) => (2, 2)
    assert (add_mult_matrices(np.array([[1,2,3],[4,5,6]]), np.array([[1,2,],[3,4],[5,6]]), 'multiply') == np.array([[22,28],[49,64]])).all()
    # Multiply matrices (2,3) @ (2,2) sizes does not conform 
    assert add_mult_matrices(np.array([[1,2,3],[4,5,6]]), np.array([[1,2],[3,4]]), 'multiply') == 'sizes must conform.'
    # don't allow an ndarray that has ndim != 2 on argument 1
    assert add_mult_matrices(np.array([[[1,2],[3,4]]]), np.array([[1,2],[3,4]]), 'multiply') == 'too many axes on ndarray'
    # don't allow an ndarray that has ndim != 2 on argument 2
    assert add_mult_matrices(np.array([[1,2],[3,4]]), np.array([[[1,2],[3,4]]]), 'multiply') == 'too many axes on ndarray'
ipytest.run()

.                                                                                            [100%]
1 passed in 0.01s


<ExitCode.OK: 0>

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [117]:
print('excersises 10.1.1')
x = np.array([[4,3]])
print(f'a = {x.shape}')
print(f'b = {5*x}')
print(f'c = {3*x}')
print(f'd = {5*x + 3*x}')
print(f'e = {8*x}')
print(f'f = {4*x - x}')
x_t = x.T
print(f'g = {x_t}')
print(f'g = {x_t.shape}')
# h
#(1,2) + (2,1) is not defined
print(f'i = {np.sqrt(np.sum(x**2))}')

print('\nexcersises 10.1.2')
v = np.array([[3],[7],[0],[11]])
print(f'a = {v.shape}')
print(f'b = {2*v}')
print(f'c = {5*v + 2*v}')
print(f'd = {4*v - 2*v}')
print(f'e = {v.T.shape}')
print(f'f = {np.sqrt(np.sum(v.T**2))}')

print('\nexcersises 10.1.3')
v1 = np.array([[4,3,1,5]])
v2 = np.array([[2,3,1,1]])
print(f'a = {np.sqrt(np.sum(v1**2))}')
print(f'b = {np.sqrt(np.sum((v1 - v2)**2))}')

excersises 10.1.1
a = (1, 2)
b = [[20 15]]
c = [[12  9]]
d = [[32 24]]
e = [[32 24]]
f = [[12  9]]
g = [[4]
 [3]]
g = (2, 1)
i = 5.0

excersises 10.1.2
a = (4, 1)
b = [[ 6]
 [14]
 [ 0]
 [22]]
c = [[21]
 [49]
 [ 0]
 [77]]
d = [[ 6]
 [14]
 [ 0]
 [22]]
e = (1, 4)
f = 13.379088160259652

excersises 10.1.3
a = 7.14142842854285
b = 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [121]:
print('\nexcersises 10.2.1')
A = np.array([[2,1,-1],[1,-1,1]])
B = np.array([[4,-2,1],[2,-4,-2]])
C = np.array([[1,2],[2,1]])
D = np.array([[3,4],[4,3]])
E = np.array([[1],[2]])
I = np.array([[1,0],[0,1]])
print(f'a = {2*A}')
print(f'b = {B - (2*A)}')
print('c = not defined')
print(f'd = {(2*D) - (3*C)}')
print(f'e = {D.T + (2*D)}')
print(f'f = {(2*C.T) - (2*D.T)}')
print('g = not defined')
print('h = not defined')
print(f'i = {C@D}')
print(f'j = {C@B}')
print(f'k = {C@I}')
print(f'l = {A@B.T}')

print('\nexcersise 10.2.2')
A = np.array([[2,3,4],[5,4,1]])
print(f'AAT = {A@A.T}')

print('\nexcersise 10.2.3')
A = np.array([[1,2],[2,4]])
B = np.array([[2,1],[1,3]])
C = np.array([[4,3],[0,2]])

#verifiera AB = AC men att B ̸= C.
print(f'AB = {A@B}')
print(f'AC = {A@C}')
print(f'AB = AC is {np.array_equal(A@B, A@C)}')
print(f'B ̸= C is {np.array_equal(B, C) == False}')


excersises 10.2.1
a = [[ 4  2 -2]
 [ 2 -2  2]]
b = [[ 0 -4  3]
 [ 0 -2 -4]]
c = not defined
d = [[3 2]
 [2 3]]
e = [[ 9 12]
 [12  9]]
f = [[-4 -4]
 [-4 -4]]
g = not defined
h = not defined
i = [[11 10]
 [10 11]]
j = [[  8 -10  -3]
 [ 10  -8   0]]
k = [[1 2]
 [2 1]]
l = [[5 2]
 [7 4]]

excersise 10.2.2
AAT = [[29 26]
 [26 42]]

excersise 10.2.3
AB = [[ 4  7]
 [ 8 14]]
AC = [[ 4  7]
 [ 8 14]]
AB = AC is True
B ̸= C is True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [127]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

print(f'is v1 a copy = {v1.base is None}')
print(f'is v2 a copy = {v2.base is None}')

v2[-1] = 123
print(v1)
# v1 will also have 123 on the last index because v2 is a view

[0 1 2 3]
[2 3]
is v1 a copy = True
is v2 a copy = False
[  0   1   2 123]


In [128]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[  0   1   2 123]


In [129]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
